// Login
export const HANDLE_LOGIN_CHANGE = 'HANDLE_LOGIN_CHANGE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// Register
export const HANDLE_REGISTER_CHANGE = 'HANDLE_REGISTER_CHANGE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Profile
export const HANDLE_PROFILE_INFOR_CHANGE = 'HANDLE_PROFILE_CHANGE';
export const HANDLE_PROFILE_DATA_CHANGE = 'HANDLE_PROFILE_DATA_CHANGE';
export const HANDLE_PROFILE_SKILLS_CHANGE = 'HANDLE_PROFILE_SKILLS_CHANGE';
export const HANDLE_PROFILE_AVATAR_CHANGE = 'HANDLE_PROFILE_AVATAR_CHANGE';
export const HANDLE_PROFILE_STEP_CHANGE = 'HANDLE_PROFILE_STEP_CHANGE';
export const HANDLE_PROFILE_STEP_BACK = 'HANDLE_PROFILE_STEP_BACK';
export const HANDLE_PROFILE_STEP_NEXT = 'HANDLE_PROFILE_STEP_NEXT';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

// Create Contract
export const HANDLE_CREATE_CONTRACT_DATA_CHANGE = 'HANDLE_CREATE_CONTRACT_DATA_CHANGE';
export const HANDLE_CREATE_CONTRACT_SKILL_CHANGE = 'HANDLE_CREATE_CONTRACT_SKILL_CHANGE';
export const HANDLE_CREATE_CONTRACT_DATE_START_CHANGE = 'HANDLE_CREATE_CONTRACT_DATE_START_CHANGE';
export const HANDLE_CREATE_CONTRACT_DATE_END_CHANGE = 'HANDLE_CREATE_CONTRACT_DATE_END_CHANGE';
export const HANDLE_CREATE_CONTRACT_SET_ID_USER = 'HANDLE_CREATE_CONTRACT_SET_ID_USER';

export const CREATE_CONTRACT_REQUEST = 'CREATE_CONTRACT_REQUEST';
export const CREATE_CONTRACT_SUCCESS = 'CREATE_CONTRACT_SUCCESS';
export const CREATE_CONTRACT_FAILURE = 'CREATE_CONTRACT_FAILURE';

// Chat room
export const HANDLE_RELOAD_CHAT_ROOM = 'HANDLE_RELOAD_CHAT_ROOM';
export const HANDLE_MESSAGE_CHAT_ROOM = 'HANDLE_MESSAGE_CHAT_ROOM';

// Search
export const HANDLE_SEARCH_DATA = 'HANDLE_SEARCH_DATA';
export const HANDLE_SEARCH_RESULT = 'HANDLE_SEARCH_RESULT';
// Contract Management
export const HANDLE_CONTROLLER_SELECT_CONTRACT_MANAGEMENT = 'HANDLE_CONTROLLER_SELECT_CONTRACT_MANAGEMENT'
export const HANDLE_LOAD_LIST_CONTRACT_MANAGEMENT = 'HANDLE_LOAD_LIST_CONTRACT_MANAGEMENT'

// Contract Action
export const HANDLE_COMPLAIN_DATA_CHANGE = 'HANDLE_COMPLAIN_DATA_CHANGE'
export const HANDLE_REVIEW_DATA_CHANGE = 'HANDLE_REVIEW_DATA_CHANGE'
export const HANDLE_CONTRACT_CONTROLLER_SELECT = 'HANDLE_CONTRACT_CONTROLLER_SELECT'
// Alert
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const CLEAR = 'CLEAR';
