// Login
export const HANDLE_LOGIN_CHANGE = 'HANDLE_LOGIN_CHANGE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

// Register
export const HANDLE_REGISTER_CHANGE = 'HANDLE_REGISTER_CHANGE'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

// Profile
export const HANDLE_PROFILE_INFOR_CHANGE = 'HANDLE_PROFILE_CHANGE'
export const HANDLE_PROFILE_DATA_CHANGE = 'HANDLE_PROFILE_DATA_CHANGE'
export const HANDLE_PROFILE_AVATAR_CHANGE = 'HANDLE_PROFILE_AVATAR_CHANGE'
export const HANDLE_PROFILE_STEP_CHANGE = 'HANDLE_PROFILE_STEP_CHANGE'
export const HANDLE_PROFILE_STEP_BACK = 'HANDLE_PROFILE_STEP_BACK'
export const HANDLE_PROFILE_STEP_NEXT = 'HANDLE_PROFILE_STEP_NEXT'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAILURE = 'PROFILE_FAILURE'

// Alert
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'
export const CLEAR = 'CLEAR'